// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	
		int N = Integer.parseInt(args[0]);
		double countless = 0;
		double countgreater = 0;

		for(int i = 0; i < N; i ++) {
			if (Math.random() < 0.5){
			countless ++;
			}
			else{
				countgreater ++;
			}


		}
		double e = countless / countgreater;

		if(e != 0) {

		
		System.out.println(" > 0.5:  " + countless + " times ");
		System.out.println(" <= 0.5: " + countgreater + " times ");
		System.out.println("Ratio:  " + e);

	 }
	 	else{
		System.out.println("> 0.5:" + countless + " times ");
		System.out.println("<= 0.5:" + countgreater + " times ");

	 }	
	}
}
